[project]
name = "playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyspellchecker==0.8.2",
    "watchfiles==1.0.4",
]
